name: team_scheduler
description: Team Scheduler - Auto slot finder (Flutter + Supabase + BLoC)

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  supabase_flutter: ^2.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  image_picker: ^1.0.0
  intl: ^0.18.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
